# Generated by Django 4.2.5 on 2023-11-02 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='funcionarios_gadma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iden', models.CharField(max_length=100, null=True, verbose_name='Cedula')),
                ('ent_nombre', models.CharField(max_length=100, null=True, verbose_name='Nombres')),
                ('ent_apellido', models.CharField(max_length=200, null=True, verbose_name='Apellidos')),
                ('ent_ingreso', models.CharField(verbose_name='Fecha Ingreso')),
                ('ent_salida', models.CharField(null=True, verbose_name='Fecha Salida')),
                ('ent_cargo', models.CharField(max_length=200, null=True, verbose_name='Cargos ')),
                ('ent_sexo', models.CharField(max_length=2, null=True, verbose_name='Sexo')),
                ('dep_nombre', models.CharField(max_length=70, null=True, verbose_name='Departamento')),
            ],
        ),
    ]
