# Generated by Django 4.2.5 on 2023-11-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCatastroAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ficha_mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('det_asig_numero', models.CharField(max_length=100, null=True, verbose_name='det_asig_numero')),
                ('act_fi_identificador', models.CharField(max_length=100, null=True, verbose_name='act_fi_identificador')),
                ('asig_identificador', models.CharField(max_length=200, null=True, verbose_name='asig_identificador')),
                ('act_fi_codigo', models.CharField(max_length=50, null=True, verbose_name='act_fi_codigo ')),
                ('act_fi_nombre', models.CharField(max_length=100, null=True, verbose_name='act_fi_nombre')),
                ('act_fi_tipo', models.CharField(max_length=5, null=True, verbose_name='act_fi_tipo')),
                ('act_fi_nivel', models.CharField(max_length=100, null=True, verbose_name='act_fi_nivel')),
                ('act_fi_marca', models.CharField(max_length=100, null=True, verbose_name='act_fi_marca')),
                ('act_fi_modelo', models.CharField(max_length=70, null=True, verbose_name='act_fi_modelo')),
                ('act_fi_serie', models.CharField(max_length=70, null=True, verbose_name='act_fi_serie')),
                ('act_fi_color', models.CharField(max_length=70, null=True, verbose_name='act_fi_color')),
                ('act_fi_accesorios', models.CharField(max_length=70, null=True, verbose_name='act_fi_accesorios')),
                ('act_fi_valor_compra', models.CharField(max_length=70, null=True, verbose_name='act_fi_valor_compra')),
                ('act_fi_fecha_compra', models.CharField(max_length=70, null=True, verbose_name='act_fi_fecha_compra')),
                ('act_fi_vida_util', models.CharField(max_length=70, null=True, verbose_name='act_fi_vida_util')),
                ('act_fi_dep_acum', models.CharField(max_length=70, null=True, verbose_name='act_fi_dep_acum')),
                ('act_fi_estado', models.CharField(max_length=70, null=True, verbose_name='act_fi_estado')),
                ('act_fi_dep_periodo', models.CharField(max_length=70, null=True, verbose_name='act_fi_dep_periodo')),
                ('act_fi_cuad_contab', models.CharField(max_length=70, null=True, verbose_name='act_fi_cuad_contab')),
                ('act_fi_cantidad', models.CharField(max_length=70, null=True, verbose_name='act_fi_cantidad')),
                ('act_fi_condicion', models.CharField(max_length=70, null=True, verbose_name='act_fi_condicion')),
                ('act_fi_estCompra', models.CharField(max_length=70, null=True, verbose_name='act_fi_estCompra')),
                ('act_fi_valor_reval', models.CharField(max_length=70, null=True, verbose_name='act_fi_valor_reval')),
                ('act_fi_asignado', models.CharField(max_length=70, null=True, verbose_name='act_fi_asignado')),
                ('act_fi_factura', models.CharField(max_length=70, null=True, verbose_name='act_fi_factura')),
                ('act_fi_capitaliza', models.CharField(max_length=70, null=True, verbose_name='act_fi_capitaliza')),
                ('act_fi_fecha_ingreso', models.CharField(max_length=70, null=True, verbose_name='act_fi_fecha_ingreso')),
                ('act_fi_codigo_mef', models.CharField(max_length=70, null=True, verbose_name='act_fi_codigo_mef')),
                ('asig_fecha', models.CharField(max_length=70, null=True, verbose_name='asig_fecha')),
                ('ent_traspaso', models.CharField(max_length=70, null=True, verbose_name='ent_traspaso')),
                ('det_asig_asignado', models.CharField(max_length=70, null=True, verbose_name='det_asig_asignado')),
                ('det_asig_estado', models.CharField(max_length=70, null=True, verbose_name='det_asig_estado')),
                ('det_asig_observacion', models.CharField(max_length=70, null=True, verbose_name='det_asig_observacion')),
                ('det_asig_valor', models.CharField(max_length=70, null=True, verbose_name='det_asig_valor')),
            ],
        ),
    ]
