# Generated by Django 4.2.5 on 2023-11-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCatastroAPP', '0002_ficha_mantenimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha_mantenimiento',
            name='act_fi_cantidad',
        ),
        migrations.RemoveField(
            model_name='ficha_mantenimiento',
            name='act_fi_capitaliza',
        ),
        migrations.RemoveField(
            model_name='ficha_mantenimiento',
            name='act_fi_codigo_mef',
        ),
        migrations.RemoveField(
            model_name='ficha_mantenimiento',
            name='act_fi_cuad_contab',
        ),
        migrations.RemoveField(
            model_name='ficha_mantenimiento',
            name='act_fi_dep_acum',
        ),
        migrations.RemoveField(
            model_name='ficha_mantenimiento',
            name='act_fi_dep_periodo',
        ),
        migrations.RemoveField(
            model_name='ficha_mantenimiento',
            name='act_fi_estCompra',
        ),
        migrations.RemoveField(
            model_name='ficha_mantenimiento',
            name='act_fi_fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='ficha_mantenimiento',
            name='act_fi_valor_reval',
        ),
        migrations.RemoveField(
            model_name='ficha_mantenimiento',
            name='asig_fecha',
        ),
        migrations.RemoveField(
            model_name='ficha_mantenimiento',
            name='asig_identificador',
        ),
        migrations.RemoveField(
            model_name='ficha_mantenimiento',
            name='det_asig_asignado',
        ),
        migrations.RemoveField(
            model_name='ficha_mantenimiento',
            name='det_asig_estado',
        ),
        migrations.RemoveField(
            model_name='ficha_mantenimiento',
            name='det_asig_valor',
        ),
        migrations.RemoveField(
            model_name='ficha_mantenimiento',
            name='ent_traspaso',
        ),
        migrations.AlterField(
            model_name='ficha_mantenimiento',
            name='det_asig_observacion',
            field=models.CharField(verbose_name='det_asig_observacion'),
        ),
    ]
