# Generated by Django 4.2.5 on 2023-11-28 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myCatastroAPP', '0003_remove_ficha_mantenimiento_act_fi_cantidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='historial_mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mantenimiento', models.CharField(choices=[('Preventivo', 'Preventivo'), ('Correctivo', 'Correctivo'), ('Dardebaja', 'Dardebaja')], max_length=20, null=True, verbose_name='Tipo Mantenimiento')),
                ('observaciones', models.CharField(max_length=300, null=True, verbose_name='observaciones')),
                ('fecha_mantenimiento', models.DateField(null=True, verbose_name='Fecha Solicitud')),
                ('funcionario_encargado', models.CharField(max_length=70, null=True, verbose_name='Funcionario')),
                ('id_ficha_mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myCatastroAPP.ficha_mantenimiento', verbose_name='ficha_mantenimiento')),
            ],
        ),
    ]
