# Generated by Django 4.2.5 on 2023-12-27 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCatastroAPP', '0004_historial_mantenimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial_mantenimiento',
            name='fecha_mantenimiento',
            field=models.CharField(null=True, verbose_name='Fecha Solicitud'),
        ),
    ]
